# Generated by Django 5.1.7 on 2025-03-29 18:07

from django.db import migrations

def add_category_data(apps, schema_editor):
    # Get the Category model
    Category = apps.get_model('core', 'Category')

    # Predefined categories
    categories = [
        {"name": "Food", "color": "#FF5733", "icon": "fa-utensils"},
        {"name": "Transport", "color": "#33FF57", "icon": "fa-bus"},
        {"name": "Entertainment", "color": "#3357FF", "icon": "fa-film"},
        {"name": "Health", "color": "#FF33A1", "icon": "fa-heartbeat"},
        {"name": "Education", "color": "#FFC300", "icon": "fa-book"},
    ]

    # Insert categories into the database
    for category_data in categories:
        Category.objects.create(
            name=category_data["name"],
            color=category_data["color"],
            icon=category_data["icon"]
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_category_user_remove_video_categories_and_more'),  # Replace with the last migration file name
    ]

    operations = [
        migrations.RunPython(add_category_data),
    ]