# Generated by Django 5.1.7 on 2025-03-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_expense_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipt',
        ),
    ]
