# Generated by Django 5.1.7 on 2025-03-31 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_expense_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipt',
        ),
    ]
