# Generated by Django 5.1.7 on 2025-03-31 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_expense_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expense_receipts/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
