# Generated by Django 5.1.7 on 2025-04-03 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='VideoLike',
        ),
    ]
