# Generated by Django 5.1.7 on 2025-04-03 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_finance_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='nb_of_likes',
        ),
    ]
