# Generated by Django 4.2.10 on 2025-04-03 04:04
from django.db import migrations

def delete_all_videos(apps, schema_editor):
    Video = apps.get_model('core', 'Video')  # Replace 'your_app_name'
    Video.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_video_nb_of_likes'),
    ]

    operations = [
        migrations.RunPython(delete_all_videos),
    ]