# Generated by Django 5.1.7 on 2025-04-03 00:48
from django.db import migrations
from django.conf import settings
import uuid

def add_initial_videos(apps, schema_editor):
    Video = apps.get_model('core', 'Video')  # Replace 'your_app_name'

    videos_data = [
        {
            'title': 'Investing Tips for Beginners',
            'url': 'http://www.youtube.com/watch?v=b5BsywkETfU',
            'thumbnail': 'https://i.ytimg.com/vi/b5BsywkETfU/mqdefault.jpg',
            'description': 'Investing Tips for Beginners',
        },
        {
            'title': 'Investing Tips for Beginners',
            'url': 'http://www.youtube.com/watch?v=1OF53QNbMrE',
            'thumbnail': 'https://i.ytimg.com/vi/1OF53QNbMrE/mqdefault.jpg',
            'description': 'Investing Tips for Beginners',
        },
        {
            'title': 'The Difference Between Saving, Investing, and Speculating',
            'url': 'http://www.youtube.com/watch?v=blnbxbftme0',
            'thumbnail': 'https://i.ytimg.com/vi/blnbxbftme0/mqdefault.jpg',
            'description': 'The Difference Between Saving, Investing, and Speculating',
        },
        {
            'title': 'Saving vs Investing',
            'url': 'http://www.youtube.com/watch?v=Oj-UpJ2STC0',
            'thumbnail': 'https://i.ytimg.com/vi/Oj-UpJ2STC0/mqdefault.jpg',
            'description': 'Saving vs Investing',
        },
        {
            'title': 'What is Investing? A Simple Explanation for Kids and Beginners',
            'url': 'http://www.youtube.com/watch?v=Epzr8azlxp8',
            'thumbnail': 'https://i.ytimg.com/vi/Epzr8azlxp8/mqdefault.jpg',
            'description': 'What is Investing? A Simple Explanation for Kids and Beginners',
        },
        {
            'title': '20 Frugal & Money Saving Tips 💰 These Changed My Life',
            'url': 'http://www.youtube.com/watch?v=BIibwcA48jg',
            'thumbnail': 'https://i.ytimg.com/vi/BIibwcA48jg/mqdefault.jpg',
            'description': '20 Frugal & Money Saving Tips 💰 These Changed My Life',
        },
        {
            'title': 'How To Save $10K FAST (Money Saving Tips)',
            'url': 'http://www.youtube.com/watch?v=paeHxkPRFoc',
            'thumbnail': 'https://i.ytimg.com/vi/paeHxkPRFoc/mqdefault.jpg',
            'description': 'How To Save $10K FAST (Money Saving Tips)',
        },
        {
            'title': 'Money saving tips for young broke adults 🤑',
            'url': 'http://www.youtube.com/watch?v=guBsd2rD2lc',
            'thumbnail': 'https://i.ytimg.com/vi/guBsd2rD2lc/mqdefault.jpg',
            'description': 'Money saving tips for young broke adults 🤑',
        },
        {
            'title': 'How to Save $5K FAST in 2025 (Money Saving Tips)',
            'url': 'http://www.youtube.com/watch?v=iLuvUqLwMgA',
            'thumbnail': 'https://i.ytimg.com/vi/iLuvUqLwMgA/mqdefault.jpg',
            'description': 'How to Save $5K FAST in 2025 (Money Saving Tips)',
        },
        {
            'title': '30 Useful Money-Saving Tips (these will help you SAVE money every month!)',
            'url': 'http://www.youtube.com/watch?v=mRa7OAvGpmQ',
            'thumbnail': 'https://i.ytimg.com/vi/mRa7OAvGpmQ/mqdefault.jpg',
            'description': '30 Useful Money-Saving Tips (these will help you SAVE money every month!)',
        },
        {
            'title': 'My 6-step Payday Routine. Full guide 👆 #shorts #payday #personalfinance',
            'url': 'http://www.youtube.com/watch?v=RIOcs8stB6w',
            'thumbnail': 'https://i.ytimg.com/vi/RIOcs8stB6w/mqdefault.jpg',
            'description': 'My 6-step Payday Routine. Full guide 👆 #shorts #payday #personalfinance',
        },
        {
            'title': '10 Crucial Personal Finance Lessons That Transformed My Life',
            'url': 'http://www.youtube.com/watch?v=Izw-xaVkO0g',
            'thumbnail': 'https://i.ytimg.com/vi/Izw-xaVkO0g/mqdefault.jpg',
            'description': '10 Crucial Personal Finance Lessons That Transformed My Life',
        },
        {
            'title': 'These Are The Steps To Manage Your Money | Personal Finance Basics',
            'url': 'http://www.youtube.com/watch?v=UcAY6qRHlw0',
            'thumbnail': 'https://i.ytimg.com/vi/UcAY6qRHlw0/mqdefault.jpg',
            'description': 'These Are The Steps To Manage Your Money | Personal Finance Basics',
        },
        {
            'title': "The BEST Financial Advice You'll Hear Today!",
            'url': 'http://www.youtube.com/watch?v=0GxSnWSp3VM',
            'thumbnail': 'https://i.ytimg.com/vi/0GxSnWSp3VM/mqdefault.jpg',
            'description': "The BEST Financial Advice You'll Hear Today!",
        },
        {
            'title': 'How to start investing—responsibly | Thomas Kehl | TEDxHSGSalon',
            'url': 'http://www.youtube.com/watch?v=FXjHwQ6J_yI',
            'thumbnail': 'https://i.ytimg.com/vi/FXjHwQ6J_yI/mqdefault.jpg',
            'description': 'How to start investing—responsibly | Thomas Kehl | TEDxHSGSalon',
        },
        {
            'title': '3 ETFs I Would ONLY Invest In As A Beginner',
            'url': 'http://www.youtube.com/watch?v=pwkKfBP0zwA',
            'thumbnail': 'https://i.ytimg.com/vi/pwkKfBP0zwA/mqdefault.jpg',
            'description': '3 ETFs I Would ONLY Invest In As A Beginner',
        },
        {
            'title': 'Investing for Beginners - How I Make Millions from Stocks (Full Guide)',
            'url': 'http://www.youtube.com/watch?v=8Ij7A1VCB7I',
            'thumbnail': 'https://i.ytimg.com/vi/8Ij7A1VCB7I/mqdefault.jpg',
            'description': 'Investing for Beginners - How I Make Millions from Stocks (Full Guide)',
        },
        {
            'title': 'Warren Buffett | How To Invest For Beginners: 3 Simple Rules',
            'url': 'http://www.youtube.com/watch?v=Uw_QyeHo8f0',
            'thumbnail': 'https://i.ytimg.com/vi/Uw_QyeHo8f0/mqdefault.jpg',
            'description': 'Warren Buffett | How To Invest For Beginners: 3 Simple Rules',
        },
    ]

    for video_data in videos_data:
        Video.objects.create(**video_data)

def remove_initial_videos(apps, schema_editor):
    Video = apps.get_model('core', 'Video')  # Replace 'your_app_name'
    Video.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_finance_videos'),
    ]

    operations = [
        migrations.RunPython(add_initial_videos, remove_initial_videos),
    ]