# Generated by Django 4.2.10 on 2025-04-03 05:16
from django.db import migrations
from django.conf import settings
import uuid

def add_four_videos(apps, schema_editor):
    Video = apps.get_model('core', 'Video')  # Replace 'your_app_name'

    four_videos_data = [
        {
            'title': 'How to Invest for Beginners in 2025',
            'url': 'https://www.youtube.com/watch?v=Ay4fmZdZqJE',
            'thumbnail': 'https://i.ytimg.com/vi/Ay4fmZdZqJE/mqdefault.jpg',  # Replace with actual thumbnail URL
            'description': 'A beginner\'s guide to investing in the year 2025.',
        },
        {
            'title': '30 Money Saving Hacks That Actually Work in 2025',
            'url': 'https://www.youtube.com/watch?v=KrQBtmB_GAM',
            'thumbnail': 'https://i.ytimg.com/vi/KrQBtmB_GAM/mqdefault.jpg',  # Replace with actual thumbnail URL
            'description': 'Effective money-saving tips and tricks for the year 2025.',
        },
        {
            'title': 'The New Rules for Building Wealth in 2025',
            'url': 'https://www.youtube.com/watch?v=TGbk79d4evQ',
            'thumbnail': 'https://i.ytimg.com/vi/TGbk79d4evQ/mqdefault.jpg',  # Replace with actual thumbnail URL
            'description': 'Understanding the evolving landscape of wealth building in 2025.',
        },
        {
            'title': 'Invest Your First $100 Like a Millionaire: Investing Guide for Beginners (2025)',
            'url': 'https://www.youtube.com/watch?v=uk2xlNDWiew',
            'thumbnail': 'https://i.ytimg.com/vi/uk2xlNDWiew/mqdefault.jpg',  # Replace with actual thumbnail URL
            'description': 'Learn how to start investing even with a small amount of money in 2025.',
        },
    ]

    for video_data in four_videos_data:
        Video.objects.create(**video_data)

def remove_four_videos(apps, schema_editor):
    Video = apps.get_model('core', 'Video')  # Replace 'your_app_name'
    titles_to_delete = [
        'How to Invest for Beginners in 2025',
        '30 Money Saving Hacks That Actually Work in 2025',
        'The New Rules for Building Wealth in 2025',
        'Invest Your First $100 Like a Millionaire: Investing Guide for Beginners (2025)',
    ]
    Video.objects.filter(title__in=titles_to_delete).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add__finance_videos'),  # Adjust this to your last migration file
    ]

    operations = [
        migrations.RunPython(add_four_videos, remove_four_videos),
    ]